### ISSUE TITLE
Fix CI errors

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/sequelize-adapter#65]
https://github.com/node-casbin/sequelize-adapter/runs/8289139592?check_suite_focus=true

Cause by PR: https://github.com/node-casbin/sequelize-adapter/pull/64

![image](https://user-images.githubusercontent.com/3787410/189509969-664ebb57-43f8-4a55-90ad-0d6c17ebed17.png)

**Comment by hsluoyz** [comment]
@rogersgt

**Comment by hsluoyz** [comment]
@js-lowes @Shivansh-yadav13 can anyone fix this? It has blocked our releasing process. If no one fixes it, I have to revert the last two PRs.

/cc @nodece

**Comment by Shivansh-yadav13** [comment]
@hsluoyz I'm working to check solution for this

**Comment by Shivansh-yadav13** [comment]
In the screenshot after running `rimraf lib && tsc` we receive this error but locally running this does not give any error like that

**Comment by Shivansh-yadav13** [comment]
@hsluoyz IG you will have to revert #64

**Comment by js-lowes** [comment]
Will take a look right now. It looks like the `tsc` command on the `prepack` is no omitting `node_modules` files and including them.

**Comment by js-lowes** [comment]
I think I found the problem. The build/release wasn't using the lockfile, so it probably was install the latest `typescript` which isn't compatible with the current repo setup instead of using the version locally.

See: https://github.com/node-casbin/sequelize-adapter/pull/68

To reproduce the problem locally run the ci step for release:
```
yarn install --no-lockfile
yarn run prepack
```

Then try it with
```
yarn install --frozen-lockfile
yarn run prepack
```


@hsluoyz Please validate the fix and merge https://github.com/node-casbin/sequelize-adapter/pull/68
